<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Cargos_model extends CI_Model
{
	public $table = "cargos";

	public function __construct()
	{
		parent::__construct();
	}

	public function listaCargos()
	{
		return $this->db->query("  SELECT id, descricao
								   FROM cargos
								   ORDER BY descricao DESC")
						->result();
	}
	
}
