<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Estados_model extends CI_Model
{
	public $table = "estados";

	public function __construct()
	{
		parent::__construct();
	}

	public function listaTodos(){
		return $this->db->select("id, nome")
			->from($this->table)
			->order_by("nome ASC")
			->get()->result();
	}

	public function listaCidadesPorEstado($estadoId){
		return $this->db->select("id, nome")
			->from("cidades")
			->where("estados_id", $estadoId)
			->order_by("capital DESC, nome ASC")
			->get()->result();
	}
	
}
