<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class EstadosCivis_model extends CI_Model
{
	public $table = "estados_civis";

	public function __construct()
	{
		parent::__construct();
	}
	
	public function listaTodos(){
		return $this->db->select("*")
			->from('estados_civis')
			->order_by("nome ASC")->get()->result();
	}
	
}
