<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Formacoes_model extends CI_Model
{
	public $table = "formacoes";

	public function __construct()
	{
		parent::__construct();
	}
	public function listaFormacoes()
	{
		return $this->db->query("  SELECT id, descricao
								   FROM formacoes
								   ORDER BY descricao DESC")
						->result();
	}
	
}
