<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Instituicoes_model extends CI_Model
{
	public $table = "instituicoes";

	public function __construct()
	{
		parent::__construct();
	}
	
	public function listaInstituicoes()
	{
		return $this->db->query("  SELECT id, descricao
								   FROM instituicoes
								   ORDER BY descricao DESC")
						->result();
	}
}
