<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Provas_model extends CI_Model
{
	public $table = "provas";

	public function __construct()
	{
		parent::__construct();
	}

	public function getListaProvas($id_prova){
		$id_prova = intval($id_prova);
			$this->db->select("p.id, p.descricao, p.ano, i.descricao AS instituicoes");
			$this->db->select("p.cargos_id, p.bancas_id, p.instituicoes_id");
			$this->db->select("c.descricao AS cargos, b.descricao AS bancas");
			$this->db->select("q.formacoes_id, f.descricao as descricoes");
			//$this->db->select("c.id AS id_cargos, b.id AS id_bancas, i.id AS id_instituicoes");
			$this->db->from("provas AS p");
			$this->db->from("questoes AS q");
			$this->db->join("instituicoes AS i", "i.id = p.instituicoes_id", "left");
			$this->db->join("bancas AS b", "b.id = p.bancas_id", "left");
			$this->db->join("cargos AS c", "c.id = p.cargos_id", "left");
			$this->db->join("formacoes AS f", "f.id = q.formacoes_id", "left");
			$this->db->where("p.id", $id_prova);
		return $this->db->get()->row();
	}
	
}
