<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Questoes_model extends CI_Model
{
	public $table = "questoes";

	public function __construct()
	{
		parent::__construct();
	}

}
